name: MasterDeployCI
on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Packages
      run: npm ci
    - name: Deploy to GH Pages  
      run: |
       git config --global user.email ${{secrets.ANDY_EMAIL}}
       git config --global user.name ${{secrets.ANDY_USERNAME}}
       git remote set-url origin https://${{secrets.PERSONAL_TOKEN}}@github.com/${{secrets.ANDY_USERNAME}}/disney-x.git
       npm run deploy
